server:
  port: 4546

greco-boot:
  url: http://localhost
  port: 4545

client.default-uri: http://localhost:4545/ws

spring:
  application:
    name: grecoboot
management:
  security:  
   enabled: false   
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: true
      enabled-by-default: false